package ecommerce_app.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Top performing product for dashboard display")
public class TopProductResponse {

  @Schema(description = "Unique product ID", example = "1")
  private Long id;

  @Schema(description = "Product name", example = "iPhone 15 Pro")
  private String name;

  @Schema(
      description = "Primary product image URL",
      example = "https://cdn.example.com/products/iphone15.jpg")
  private String image;

  @Schema(description = "Total revenue generated by this product", example = "9999.00")
  private BigDecimal revenue;

  @Schema(description = "Total quantity sold", example = "10")
  private Integer quantity;
}
