package ecommerce_app.api.admin;

import ecommerce_app.constant.message.ResponseMessageConstant;
import ecommerce_app.infrastructure.exception.BadRequestException;
import ecommerce_app.infrastructure.model.response.body.BaseBodyResponse;
import ecommerce_app.modules.category.model.dto.CategoryRequest;
import ecommerce_app.modules.category.service.CategoryExcelTemplateService;
import ecommerce_app.modules.category.service.CategoryService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@RestController
@RequestMapping("/api/admin/v1/categories")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "Category Management", description = "For admin manage category")
public class CategoryController {
  private final CategoryService categoryService;
  private final CategoryExcelTemplateService categoryExcelTemplateService;

  @PostMapping
  public ResponseEntity<BaseBodyResponse> createCategory(
      @RequestBody CategoryRequest categoryRequest) {
    return BaseBodyResponse.success(
        this.categoryService.saveCategory(categoryRequest),
        ResponseMessageConstant.CREATE_SUCCESSFULLY);
  }

  @DeleteMapping("/{id}")
  public ResponseEntity<BaseBodyResponse> deleteCategory(@PathVariable(value = "id") Long id) {
    this.categoryService.deleteCategory(id);
    return BaseBodyResponse.success(null, ResponseMessageConstant.DELETE_SUCCESSFULLY);
  }

  @GetMapping("/{id}")
  public ResponseEntity<BaseBodyResponse> getById(@PathVariable(value = "id") Long id) {
    return BaseBodyResponse.success(
        categoryService.getCategoryById(id), ResponseMessageConstant.FIND_ONE_SUCCESSFULLY);
  }

  @PutMapping("/{id}")
  public ResponseEntity<BaseBodyResponse> updateCategory(
      @RequestBody CategoryRequest categoryRequest, @PathVariable(value = "id") Long id) {
    return BaseBodyResponse.success(
        categoryService.updateCategory(categoryRequest, id),
        ResponseMessageConstant.UPDATE_SUCCESSFULLY);
  }

  @GetMapping("/name/{name}")
  public ResponseEntity<BaseBodyResponse> getByName(@PathVariable(value = "name") String name) {
    return BaseBodyResponse.success(
        categoryService.getCategoryByName(name), ResponseMessageConstant.FIND_ONE_SUCCESSFULLY);
  }

  @GetMapping
  public ResponseEntity<BaseBodyResponse> filter(
      @RequestParam(value = "isPaged", defaultValue = "true") boolean isPaged,
      @RequestParam(value = "page", defaultValue = "1") int page,
      @RequestParam(value = "pageSize", defaultValue = "10") int pageSize,
      @RequestParam(value = "sortBy", defaultValue = "createdAt") String sortBy,
      @RequestParam(value = "sortDirection", defaultValue = "DESC") Sort.Direction sortDirection,
      @RequestParam(value = "filter", required = false) String filter) {
    return BaseBodyResponse.pageSuccess(
        categoryService.filter(isPaged, page, pageSize, sortBy, sortDirection, filter),
        ResponseMessageConstant.FIND_ALL_SUCCESSFULLY);
  }

  /** Download Excel template for category import with dynamic sample data */
  @GetMapping("/import-template")
  //  @PreAuthorize("hasAnyRole('ADMIN', 'USER')")
  @Operation(
      summary = "Download category import template",
      description = "Generate and download Excel template with optional sample data")
  public ResponseEntity<Resource> getTemplateImportExcel(
      @Parameter(description = "Number of sample rows to generate (0-100)", name = "rows")
          @RequestParam(defaultValue = "5")
          int rows,
      @Parameter(description = "Include sample data generated by Faker", name = "includeSampleData")
          @RequestParam(defaultValue = "true")
          boolean includeSampleData) {

    // Validate rows parameter
    if (rows < 0 || rows > 100) {
      throw new BadRequestException("'rows' parameter must be between 0 and 1000");
    }

    log.info(
        "Generating categories import template (rows: {}, includeSampleData: {})",
        rows,
        includeSampleData);

    byte[] excelData = categoryExcelTemplateService.generateCategoryExcelTemplate(rows);

    ByteArrayResource resource = new ByteArrayResource(excelData);

    // Generate filename with timestamp
    String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
    String filename = String.format("categories_import_template_%s.xlsx", timestamp);

    return ResponseEntity.ok()
        .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")
        .contentType(
            MediaType.parseMediaType(
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))
        .contentLength(excelData.length)
        .body(resource);
  }
}
